## ADD WHATEVER ARGUMENTS ARE NECESSARY TO THE MAIN FUNCTION
## IN THE SAME ORDER AS THE ARGUMENTS ARE PASSED TO THE CALL
## TO THE main() FUNCTION SPECIFIED BELOW
def main() :
	## DO NOT REMOVE THIS LINE
	max = 0 ## VARIABLE 'max' SHOULD STORE THE MAXIMUM NUMBER
	        ## OF CONSECUTIVE CAG TRI-NUCLEOTIDES

	## YOUR CODE SHOULD START HERE!!

	## YOU CODE SHOULD END HERE!!

	## DO NOT REMOVE THIS LINE, IT SHOULD RETURN THE MAXIMUM
	## NUMBER OF CONSECUTIVE CAG TRI-NUCLEOTIDES
	return(max)

## DO NOT REMOVE THIS LINE BELOW
if __name__ == "__main__" :

	## MODIFY THE LINE BELOW AND ADD BEFORE WHATEVER LINES ARE NECESSARY
	## TO RUN THIS PROGRAM AS:
	## $ python src/cagrepeatmax.py <filename>
	print(main())
